name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: cd apps/backend && npm install
      - run: cd apps/backend && npx prisma generate
      - run: cd apps/backend && DATABASE_URL=postgresql://test:test@localhost:5432/test npx prisma migrate dev --name init
      - run: cd apps/backend && npm test
      - run: cd apps/backend && npm run lint

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: cd apps/backend && npm install
      - run: cd apps/backend && npm run build